### ISSUE TITLE
Upload pre trained Model 

### ISSUE THREAD

**Issue by kousik97** [LamUong/DjangoWithCNN#3]
Can you please upload the pre trained model.

**Comment by LamUong** [comment]
I do not have any pre trained model. It was just random weight initialization.

**Comment by kousik97** [comment]
The results that I am getting are quite different from the one shown in the Django App. That is why I asked for the pre trained model .

**Comment by LamUong** [comment]
Hi Kousik97,

I do not have a pre-trained model. The code I gave you is all I used. I initialize the weight randomly.

Thanks,

Lam

________________________________
